export enum AppConfig {
  BTN_LOADER_PRIMARY_COLOR = 'primary',
  BTN_LOADER_DIAMETER = 20,
  BTN_LOADER_DIAMETER_SMALL = 15,
}

export enum Solutions {
  SMART_STORES = 'SMART_STORES',
  SMART_LOGISTICS = 'SMART_LOGISTICS',
  SMART_FACTORIES = 'SMART_FACTORIES',
  SMART_GC = 'SMART_GC',
}
